CREATE TABLE IF NOT EXISTS order_workflow (
  id INT AUTO_INCREMENT PRIMARY KEY,
  netsuite_id INT NOT NULL UNIQUE,
  updated_by BIGINT,
  selected_departments TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_responses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  netsuite_id INT NOT NULL,
  department VARCHAR(255) NOT NULL,
  action VARCHAR(20) NOT NULL,
  remark TEXT,
  responded_by BIGINT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
